export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENT_FAILED = 'FETCH_INGREDIENT_FAILED';

export const PURCASE_BURGER_SUCCESS = 'PURCASE_BURGER_SUCCESS';
export const PURCASE_BURGER_FAIL = 'PURCASE_BURGER_FAIL';
